# Default values for chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: heliumdatastage/pod-reaper
  tag: v0.0.1

# A set of named reapers
# Example config:
#
reapers: 
  helx-reaper:
    namespace: ""
    grace_period: 10m
    schedule: "@every 1m"
    run_duration: "0s"
    require_label_key: "executor"
    require_label_values: "tycho"
    dry_run: "false"
    log_level: "Info"
    log_format: "Logrus"
    max_duration: "1m"
resources:
  limits:
    cpu: 30m
    memory: 30Mi
  requests:
    cpu: 20m
    memory: 20Mi
